### ISSUE TITLE
[Add] Module usage (their scripts to use) on README.md

### ISSUE THREAD

**Issue by danimesq** [BridgeAR/fast-json-escape#2]
@BridgeAR

**Comment by BridgeAR** [comment]
@danimesq would you be so kind and elaborate? I am not sure what exactly you would like me to describe.

**Comment by danimesq** [comment]
@BridgeAR
What is the script to make escaped json and the unescaped?
How to integrate it with a Electron app with declare?
Is that what I mean by script/module usage.

**Comment by BridgeAR** [comment]
I am sorry, I am still not fully understanding. I seemed to have missed this issue for a long time but I guess it might be about what parts would be escaped? That is for example half surrogate pairs or e.g., `\r\n`.
I don't believe that should be documented as it is independent from this module and just about JSON.stringify().
